sonar.projectKey=ObjectIdPlugin
sonar.sourceEncoding=UTF-8
# only analyzing actual library source
sonar.sources=src
# exclude unit tests from coverage and analysis
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/testing/*
# tell sonar where to find coverage results
sonar.typescript.lcov.reportPaths=coverage/lcov.info